### ISSUE TITLE
JSONb output option

### ISSUE THREAD

**Issue by ppKrauss** [pnorman/ClearTables#98]
Migrating from [issue#533 of openstreetmap/osm2pgsql](https://github.com/openstreetmap/osm2pgsql/issues/533). 

----

About  [util.lua#L48-L59](https://github.com/ClearTables/ClearTables/blob/v0.0.4/util.lua#L48-L59): I need time to analyse and test it... Understanding that your suggestion is to modify, creating a `function jsonb (table)`  by copy/paste and changing `=>` to `:` at variable `s`.... But there are some other issues to check in the lua library, as illustrated by this SQL lines:

```sql
SELECT  '"x"=>"foo", "y"=>"bar"'::hstore;  -- is valid!
SELECT  '"x":"foo", "y":"bar"'::JSONb;  -- SYNTAX ERROR
SELECT  '{"x":"foo", "y":"bar"}'::JSONb;  -- is valid! needs {folding} 

SELECT  hstore_to_jsonb('"x"=>1.12, "y"=>t'::hstore); -- interpretation ERROR
SELECT  hstore_to_jsonb_loose('"x"=>1.12, "y"=>t'::hstore); -- is valid! 
```

So another strategy is to reuse `hstore` transformation in the JSONb functions, adding only a fold `hstore_to_jsonb_loose(s)` in the final output.

**Comment by pnorman** [comment]
What columns are you proposing to use jsonb for? I've considered adding a function to make json, but I saw no use for any json columns since I had nothing which needed a multi-level structure.

**Comment by pnorman** [comment]
ping

**Comment by pnorman** [comment]
For the idea of using hstore_to_jsonb_loose, columns must be set to something which cleanly casts from text to the type of the column using the text input conversion function of the column type. The output from ClearTables goes directly to a COPY statement.

**Comment by ppKrauss** [comment]
The  use of "JSON instead HStore"  is only a matter of standardization (see eg. [recent adoption in US's NIEM](https://www.niem.gov/techhub/json)), and a first step for other uses. 

PS: about the typical ClearTables SQL COPY statements, do you have a generic syntax sample?   Perhaps we can add other SQL statements in the output.

**Comment by pnorman** [comment]
For plain key value storage of strings, I'm not switching from hstore to jsonb without benchmarks that it's considerably better with the usage patterns ClearTables has, and suitable CHECK constraints to make the jsonb equivalent to hstore in being a simple key-value storage.

As additional detail, adoption of JSON for interchange is not related to this issue, which is about the storage format in database. The main users of a ClearTables (or any OSM) database will be extracting values from the kv store, not selecting the entire kv store, so if it's jsonb, json, hstore, or something else is an implementation detail.

I see no advantages to queries which say `names->>'en'` instead of `names->'en'`. The `@>` and `?` operators aren't likely to come up with ClearTables usage, but `?` is the same with jsonb and hstore, and `@>` is easier to write with hstore.

Additionally, this only applies to multilingual names.

> PS: about the typical ClearTables SQL COPY statements, do you have a generic syntax sample? Perhaps we can add other SQL statements in the output.

ClearTables doesn't generate SQL COPY statements, it returns a table of Lua strings to osm2pgsql which inserts them into the database with either COPY (on load) or INSERT (on update). For the syntax, see the table definition - it's just loading into all the columns the values returned.

> a first step for other uses

What other uses? There might be other proposed uses where a multi-level data storage structure could be relevant yet columns aren't warranted, but you need to explain what they are.

**Comment by pnorman** [comment]
> What other uses? There might be other proposed uses where a multi-level data storage structure could be relevant yet columns aren't warranted, but you need to explain what they are.

With the lack of a suggested use for a multi-level data storage structure, I'm closing this. If a column is proposed in a new issue where it makes sense to have such a storage structure, JSON(b) is an option. Until then, writing it would just result in unused lua code.
